version: '3.8'
services:
  wallpaper:
    network_mode: host
    build:
      context: .
    image: wallpaper
    restart: on-failure:5
    container_name: wallpaper
    volumes:
      - ./pictures:/pictures

